/**
 * Curated dataset of major historical events from 1600 to present
 * Organized by century and category
 */

export const HISTORICAL_EVENTS = [
  // 1600s - Age of Exploration & Scientific Revolution
  { title: "Founding of Jamestown", year: 1607, category: "Exploration", location: "Jamestown, Virginia", description: "First permanent English settlement in North America established." },
  { title: "Galileo's Telescope Discoveries", year: 1609, category: "Science", location: "Venice, Italy", description: "Galileo Galilei makes astronomical observations that support heliocentrism." },
  { title: "King James Bible Published", year: 1611, category: "Culture", location: "London, England", description: "Authorized Version of the Bible published in English." },
  { title: "Thirty Years' War Begins", year: 1618, category: "Conflict", location: "Prague, Czech Republic", description: "Devastating European war begins with the Defenestration of Prague." },
  { title: "Mayflower Arrives at Plymouth", year: 1620, category: "Exploration", location: "Plymouth, Massachusetts", description: "Pilgrims establish Plymouth Colony in New England." },
  { title: "Dutch Found New Amsterdam", year: 1626, category: "Exploration", location: "New York City, New York", description: "Dutch settlers establish trading post that becomes New York." },
  { title: "Taj Mahal Construction Begins", year: 1632, category: "Culture", location: "Agra, India", description: "Emperor Shah Jahan begins building the iconic mausoleum." },
  { title: "English Civil War Begins", year: 1642, category: "Conflict", location: "England, United Kingdom", description: "Conflict between Parliamentarians and Royalists erupts." },
  { title: "Peace of Westphalia", year: 1648, category: "Politics", location: "Münster, Germany", description: "Treaties end Thirty Years' War and establish modern state sovereignty." },
  { title: "Great Fire of London", year: 1666, category: "Disaster", location: "London, England", description: "Devastating fire destroys much of medieval London." },
  { title: "Isaac Newton's Principia Published", year: 1687, category: "Science", location: "London, England", description: "Newton publishes laws of motion and universal gravitation." },
  { title: "Glorious Revolution", year: 1688, category: "Revolution", location: "London, England", description: "William of Orange overthrows James II in bloodless revolution." },

  // 1700s - Age of Enlightenment & Revolution
  { title: "Great Northern War Begins", year: 1700, category: "Conflict", location: "Stockholm, Sweden", description: "Coalition wars against Swedish Empire's dominance in the Baltic." },
  { title: "First Practical Steam Engine", year: 1712, category: "Technology", location: "Dudley, England", description: "Thomas Newcomen invents atmospheric steam engine." },
  { title: "Treaty of Utrecht", year: 1713, category: "Politics", location: "Utrecht, Netherlands", description: "Peace treaties ending War of Spanish Succession." },
  { title: "Bach Completes Brandenburg Concertos", year: 1721, category: "Culture", location: "Köthen, Germany", description: "Johann Sebastian Bach finishes his famous concertos." },
  { title: "Benjamin Franklin's Kite Experiment", year: 1752, category: "Science", location: "Philadelphia, Pennsylvania", description: "Franklin proves lightning is electricity with famous kite experiment." },
  { title: "Seven Years' War Begins", year: 1756, category: "Conflict", location: "Central Europe", description: "Global conflict involving most European great powers." },
  { title: "British Capture Quebec", year: 1759, category: "Conflict", location: "Quebec City, Canada", description: "Battle of the Plains of Abraham secures British control of Canada." },
  { title: "Mozart's First Symphony", year: 1764, category: "Culture", location: "London, England", description: "Eight-year-old Mozart composes Symphony No. 1." },
  { title: "James Watt Improves Steam Engine", year: 1769, category: "Technology", location: "Glasgow, Scotland", description: "Watt patents separate condenser, revolutionizing steam power." },
  { title: "Boston Tea Party", year: 1773, category: "Revolution", location: "Boston, Massachusetts", description: "American colonists dump British tea into harbor in protest." },
  { title: "American Declaration of Independence", year: 1776, category: "Revolution", location: "Philadelphia, Pennsylvania", description: "Thirteen colonies declare independence from Britain." },
  { title: "Adam Smith Publishes Wealth of Nations", year: 1776, category: "Economy", location: "London, England", description: "Foundational text of modern economics published." },
  { title: "First Fleet Arrives in Australia", year: 1788, category: "Exploration", location: "Sydney, Australia", description: "British ships arrive to establish penal colony in Australia." },
  { title: "Storming of the Bastille", year: 1789, category: "Revolution", location: "Paris, France", description: "French Revolution begins with attack on royal fortress." },
  { title: "U.S. Constitution Ratified", year: 1789, category: "Politics", location: "New York City, New York", description: "United States Constitution comes into effect." },
  { title: "First Cotton Mill in America", year: 1790, category: "Technology", location: "Pawtucket, Rhode Island", description: "Samuel Slater establishes first water-powered cotton mill." },
  { title: "Reign of Terror in France", year: 1793, category: "Conflict", location: "Paris, France", description: "Period of violence during French Revolution begins." },
  { title: "Napoleon's Egyptian Campaign", year: 1798, category: "Conflict", location: "Cairo, Egypt", description: "Napoleon invades Egypt, discovers Rosetta Stone." },

  // 1800s - Industrial Revolution & Nationalism
  { title: "Louisiana Purchase", year: 1803, category: "Politics", location: "New Orleans, Louisiana", description: "United States acquires vast territory from France." },
  { title: "Lewis and Clark Expedition", year: 1804, category: "Exploration", location: "St. Louis, Missouri", description: "Expedition to explore western North America begins." },
  { title: "Battle of Trafalgar", year: 1805, category: "Conflict", location: "Cape Trafalgar, Spain", description: "Nelson defeats Franco-Spanish fleet, ensuring British naval supremacy." },
  { title: "Beethoven's Fifth Symphony Premiered", year: 1808, category: "Culture", location: "Vienna, Austria", description: "One of the most famous symphonies in history debuts." },
  { title: "Napoleon Invades Russia", year: 1812, category: "Conflict", location: "Moscow, Russia", description: "Disastrous campaign marks beginning of Napoleon's downfall." },
  { title: "Battle of Waterloo", year: 1815, category: "Conflict", location: "Waterloo, Belgium", description: "Napoleon defeated, ending Napoleonic Wars." },
  { title: "Congress of Vienna", year: 1815, category: "Politics", location: "Vienna, Austria", description: "European powers redraw map after Napoleon's defeat." },
  { title: "First Steamship Crosses Atlantic", year: 1819, category: "Technology", location: "Savannah, Georgia", description: "SS Savannah makes first transatlantic voyage with steam power." },
  { title: "Monroe Doctrine Declared", year: 1823, category: "Politics", location: "Washington, D.C.", description: "U.S. opposes European colonialism in the Americas." },
  { title: "First Passenger Railway Opens", year: 1825, category: "Technology", location: "Stockton, England", description: "Stockton and Darlington Railway inaugurated." },
  { title: "Greek Independence", year: 1829, category: "Revolution", location: "Athens, Greece", description: "Greece wins independence from Ottoman Empire." },
  { title: "Darwin's Voyage on the Beagle", year: 1831, category: "Science", location: "Plymouth, England", description: "Charles Darwin begins voyage that leads to theory of evolution." },
  { title: "Texas Revolution", year: 1836, category: "Revolution", location: "San Antonio, Texas", description: "Texas declares independence from Mexico." },
  { title: "Queen Victoria's Reign Begins", year: 1837, category: "Politics", location: "London, England", description: "Victoria becomes Queen, beginning Victorian era." },
  { title: "First Photograph of a Person", year: 1838, category: "Technology", location: "Paris, France", description: "Louis Daguerre captures first photo including human figure." },
  { title: "Opium War Begins", year: 1839, category: "Conflict", location: "Guangzhou, China", description: "Britain wars with China over opium trade." },
  { title: "First Telegraph Message", year: 1844, category: "Technology", location: "Washington, D.C.", description: "Samuel Morse sends 'What hath God wrought' via telegraph." },
  { title: "Irish Potato Famine", year: 1845, category: "Disaster", location: "Dublin, Ireland", description: "Great Famine begins, causing mass starvation and emigration." },
  { title: "Revolutions of 1848", year: 1848, category: "Revolution", location: "Paris, France", description: "Wave of revolutions sweeps across Europe." },
  { title: "California Gold Rush", year: 1848, category: "Economy", location: "Sacramento, California", description: "Gold discovered at Sutter's Mill, triggering mass migration." },
  { title: "Communist Manifesto Published", year: 1848, category: "Politics", location: "London, England", description: "Marx and Engels publish influential political pamphlet." },
  { title: "Crimean War Begins", year: 1853, category: "Conflict", location: "Crimea, Ukraine", description: "Russia fights Ottoman Empire, France, and Britain." },
  { title: "Perry Opens Japan", year: 1854, category: "Politics", location: "Tokyo, Japan", description: "U.S. Commodore Perry forces Japan to end isolation." },
  { title: "Darwin Publishes Origin of Species", year: 1859, category: "Science", location: "London, England", description: "Revolutionary work on evolution by natural selection." },
  { title: "Italian Unification Begins", year: 1861, category: "Politics", location: "Turin, Italy", description: "Kingdom of Italy proclaimed under Victor Emmanuel II." },
  { title: "American Civil War Begins", year: 1861, category: "Conflict", location: "Charleston, South Carolina", description: "Confederate forces attack Fort Sumter." },
  { title: "Emancipation Proclamation", year: 1863, category: "Politics", location: "Washington, D.C.", description: "Lincoln declares enslaved people in rebellion states free." },
  { title: "Battle of Gettysburg", year: 1863, category: "Conflict", location: "Gettysburg, Pennsylvania", description: "Turning point of American Civil War." },
  { title: "Maxwell's Equations Published", year: 1865, category: "Science", location: "Cambridge, England", description: "James Clerk Maxwell unifies electricity and magnetism." },
  { title: "Assassination of Abraham Lincoln", year: 1865, category: "Politics", location: "Washington, D.C.", description: "President Lincoln shot by John Wilkes Booth." },
  { title: "Dynamite Invented", year: 1867, category: "Technology", location: "Stockholm, Sweden", description: "Alfred Nobel invents dynamite." },
  { title: "Meiji Restoration", year: 1868, category: "Revolution", location: "Tokyo, Japan", description: "Japan ends feudalism, begins rapid modernization." },
  { title: "Transcontinental Railroad Completed", year: 1869, category: "Technology", location: "Promontory Summit, Utah", description: "First railroad connecting U.S. coasts finished." },
  { title: "Suez Canal Opens", year: 1869, category: "Technology", location: "Port Said, Egypt", description: "Major shipping canal connecting Mediterranean and Red Sea." },
  { title: "Franco-Prussian War", year: 1870, category: "Conflict", location: "Sedan, France", description: "Prussia defeats France, leading to German unification." },
  { title: "German Empire Proclaimed", year: 1871, category: "Politics", location: "Versailles, France", description: "Wilhelm I becomes German Kaiser, unifying Germany." },
  { title: "First Telephone Call", year: 1876, category: "Technology", location: "Boston, Massachusetts", description: "Alexander Graham Bell makes first successful telephone call." },
  { title: "Edison Invents Phonograph", year: 1877, category: "Technology", location: "Menlo Park, New Jersey", description: "Thomas Edison creates first device to record and play sound." },
  { title: "First Electric Light Bulb", year: 1879, category: "Technology", location: "Menlo Park, New Jersey", description: "Edison demonstrates practical incandescent light bulb." },
  { title: "Scramble for Africa Begins", year: 1881, category: "Politics", location: "Berlin, Germany", description: "European powers begin rapid colonization of Africa." },
  { title: "Krakatoa Eruption", year: 1883, category: "Disaster", location: "Krakatoa, Indonesia", description: "Volcanic eruption kills 36,000, heard 3,000 miles away." },
  { title: "First Skyscraper Built", year: 1885, category: "Technology", location: "Chicago, Illinois", description: "Home Insurance Building, world's first skyscraper, completed." },
  { title: "Statue of Liberty Dedicated", year: 1886, category: "Culture", location: "New York City, New York", description: "France's gift to U.S. unveiled in New York Harbor." },
  { title: "Eiffel Tower Completed", year: 1889, category: "Culture", location: "Paris, France", description: "Iconic iron tower built for Paris World's Fair." },
  { title: "First Automobile Production", year: 1893, category: "Technology", location: "Springfield, Massachusetts", description: "Duryea Brothers build first American gasoline automobile." },
  { title: "Dreyfus Affair Begins", year: 1894, category: "Politics", location: "Paris, France", description: "Political scandal divides France over wrongful conviction." },
  { title: "First Modern Olympics", year: 1896, category: "Culture", location: "Athens, Greece", description: "Modern Olympic Games revived after 1,500 years." },
  { title: "Spanish-American War", year: 1898, category: "Conflict", location: "Havana, Cuba", description: "U.S. defeats Spain, gains Philippines and Puerto Rico." },
  { title: "Boer War Begins", year: 1899, category: "Conflict", location: "Pretoria, South Africa", description: "British Empire fights Boer republics in South Africa." },

  // 1900s - World Wars & Modern Era
  { title: "Boxer Rebellion", year: 1900, category: "Conflict", location: "Beijing, China", description: "Chinese nationalists attack foreign influences in China." },
  { title: "Queen Victoria Dies", year: 1901, category: "Politics", location: "Isle of Wight, England", description: "End of Victorian era after 63-year reign." },
  { title: "First Powered Flight", year: 1903, category: "Technology", location: "Kitty Hawk, North Carolina", description: "Wright Brothers achieve first controlled airplane flight." },
  { title: "Russo-Japanese War", year: 1904, category: "Conflict", location: "Manchuria, China", description: "Japan defeats Russia, becomes major world power." },
  { title: "Einstein's Special Relativity", year: 1905, category: "Science", location: "Bern, Switzerland", description: "Einstein publishes groundbreaking theory of relativity." },
  { title: "San Francisco Earthquake", year: 1906, category: "Disaster", location: "San Francisco, California", description: "Devastating earthquake and fire destroy much of city." },
  { title: "Ford Model T Introduced", year: 1908, category: "Technology", location: "Detroit, Michigan", description: "First affordable automobile for middle class debuts." },
  { title: "South Pole Reached", year: 1911, category: "Exploration", location: "South Pole, Antarctica", description: "Roald Amundsen first to reach geographic South Pole." },
  { title: "Titanic Sinks", year: 1912, category: "Disaster", location: "North Atlantic Ocean", description: "RMS Titanic hits iceberg, over 1,500 die." },
  { title: "World War I Begins", year: 1914, category: "Conflict", location: "Sarajevo, Bosnia", description: "Assassination of Archduke Franz Ferdinand triggers global war." },
  { title: "Panama Canal Opens", year: 1914, category: "Technology", location: "Panama City, Panama", description: "Canal connecting Atlantic and Pacific Oceans completed." },
  { title: "Einstein's General Relativity", year: 1915, category: "Science", location: "Berlin, Germany", description: "Einstein publishes theory of general relativity." },
  { title: "Battle of Verdun", year: 1916, category: "Conflict", location: "Verdun, France", description: "Longest WWI battle, 700,000 casualties." },
  { title: "Russian Revolution", year: 1917, category: "Revolution", location: "Petrograd, Russia", description: "Bolsheviks overthrow Russian government, establish communist state." },
  { title: "Spanish Flu Pandemic", year: 1918, category: "Disaster", location: "Global", description: "Deadliest pandemic in history, kills 50-100 million." },
  { title: "World War I Ends", year: 1918, category: "Politics", location: "Compiègne, France", description: "Armistice signed ending Great War." },
  { title: "Treaty of Versailles", year: 1919, category: "Politics", location: "Versailles, France", description: "Peace treaty formally ends WWI, reshapes Europe." },
  { title: "League of Nations Founded", year: 1920, category: "Politics", location: "Geneva, Switzerland", description: "First international organization for world peace." },
  { title: "Women's Suffrage in U.S.", year: 1920, category: "Politics", location: "Washington, D.C.", description: "19th Amendment grants women right to vote." },
  { title: "Irish Independence", year: 1921, category: "Revolution", location: "Dublin, Ireland", description: "Irish Free State established after war with Britain." },
  { title: "Discovery of Tutankhamun's Tomb", year: 1922, category: "Culture", location: "Luxor, Egypt", description: "Howard Carter finds intact pharaoh's tomb." },
  { title: "Time Magazine First Published", year: 1923, category: "Culture", location: "New York City, New York", description: "First issue of Time, world's first weekly news magazine." },
  { title: "First Winter Olympics", year: 1924, category: "Culture", location: "Chamonix, France", description: "Inaugural Winter Olympic Games held." },
  { title: "Scopes Monkey Trial", year: 1925, category: "Culture", location: "Dayton, Tennessee", description: "Teacher tried for teaching evolution in schools." },
  { title: "First Television Demonstration", year: 1926, category: "Technology", location: "London, England", description: "John Logie Baird demonstrates television system." },
  { title: "Lindbergh's Transatlantic Flight", year: 1927, category: "Exploration", location: "Paris, France", description: "Charles Lindbergh makes first solo nonstop flight across Atlantic." },
  { title: "Penicillin Discovered", year: 1928, category: "Science", location: "London, England", description: "Alexander Fleming discovers first antibiotic." },
  { title: "Wall Street Crash", year: 1929, category: "Economy", location: "New York City, New York", description: "Stock market crash triggers Great Depression." },
  { title: "Gandhi's Salt March", year: 1930, category: "Revolution", location: "Ahmedabad, India", description: "Nonviolent protest against British salt tax." },
  { title: "Empire State Building Opens", year: 1931, category: "Technology", location: "New York City, New York", description: "World's tallest building completed during Depression." },
  { title: "Neutron Discovered", year: 1932, category: "Science", location: "Cambridge, England", description: "James Chadwick discovers neutron, key to nuclear physics." },
  { title: "Hitler Becomes Chancellor", year: 1933, category: "Politics", location: "Berlin, Germany", description: "Adolf Hitler appointed German Chancellor." },
  { title: "Dust Bowl Begins", year: 1934, category: "Disaster", location: "Oklahoma, United States", description: "Severe drought devastates American Great Plains." },
  { title: "Nuremberg Laws", year: 1935, category: "Politics", location: "Nuremberg, Germany", description: "Nazi Germany enacts antisemitic legislation." },
  { title: "Spanish Civil War", year: 1936, category: "Conflict", location: "Madrid, Spain", description: "Nationalists under Franco fight Republican government." },
  { title: "Hindenburg Disaster", year: 1937, category: "Disaster", location: "Lakehurst, New Jersey", description: "German airship catches fire, ends airship era." },
  { title: "Kristallnacht", year: 1938, category: "Conflict", location: "Germany", description: "Nazi pogrom against Jews throughout Germany." },
  { title: "World War II Begins", year: 1939, category: "Conflict", location: "Warsaw, Poland", description: "Germany invades Poland, starting global conflict." },
  { title: "Battle of Britain", year: 1940, category: "Conflict", location: "London, England", description: "RAF defeats Luftwaffe, prevents German invasion." },
  { title: "Pearl Harbor Attack", year: 1941, category: "Conflict", location: "Honolulu, Hawaii", description: "Japan attacks U.S. naval base, America enters WWII." },
  { title: "Battle of Stalingrad", year: 1942, category: "Conflict", location: "Volgograd, Russia", description: "Turning point of WWII on Eastern Front." },
  { title: "D-Day Invasion", year: 1944, category: "Conflict", location: "Normandy, France", description: "Allied forces land in France, beginning liberation of Europe." },
  { title: "Yalta Conference", year: 1945, category: "Politics", location: "Yalta, Ukraine", description: "Allied leaders plan post-war world order." },
  { title: "Atomic Bomb on Hiroshima", year: 1945, category: "Conflict", location: "Hiroshima, Japan", description: "First atomic weapon used in warfare." },
  { title: "United Nations Founded", year: 1945, category: "Politics", location: "San Francisco, California", description: "International organization established to maintain peace." },
  { title: "World War II Ends", year: 1945, category: "Politics", location: "Tokyo, Japan", description: "Japan surrenders, ending Second World War." },
  { title: "Nuremberg Trials", year: 1946, category: "Politics", location: "Nuremberg, Germany", description: "Nazi war criminals prosecuted for crimes against humanity." },
  { title: "Indian Independence", year: 1947, category: "Revolution", location: "New Delhi, India", description: "India gains independence from British Empire." },
  { title: "Israel Founded", year: 1948, category: "Politics", location: "Tel Aviv, Israel", description: "State of Israel established in Middle East." },
  { title: "Berlin Airlift", year: 1948, category: "Politics", location: "Berlin, Germany", description: "Western Allies supply West Berlin during Soviet blockade." },
  { title: "NATO Founded", year: 1949, category: "Politics", location: "Washington, D.C.", description: "North Atlantic Treaty Organization established." },
  { title: "People's Republic of China", year: 1949, category: "Revolution", location: "Beijing, China", description: "Mao Zedong proclaims communist People's Republic." },
  { title: "Korean War Begins", year: 1950, category: "Conflict", location: "Seoul, South Korea", description: "North Korea invades South, U.S. intervenes." },
  { title: "Rosenbergs Executed", year: 1953, category: "Politics", location: "New York City, New York", description: "Couple executed for espionage during Red Scare." },
  { title: "DNA Structure Discovered", year: 1953, category: "Science", location: "Cambridge, England", description: "Watson and Crick determine double helix structure." },
  { title: "Brown v. Board of Education", year: 1954, category: "Politics", location: "Washington, D.C.", description: "Supreme Court ends school segregation in U.S." },
  { title: "Warsaw Pact Formed", year: 1955, category: "Politics", location: "Warsaw, Poland", description: "Soviet bloc creates military alliance." },
  { title: "Hungarian Revolution", year: 1956, category: "Revolution", location: "Budapest, Hungary", description: "Uprising against Soviet rule crushed by Red Army." },
  { title: "Sputnik Launched", year: 1957, category: "Technology", location: "Baikonur, Kazakhstan", description: "Soviet Union launches first artificial satellite." },
  { title: "Cuban Revolution", year: 1959, category: "Revolution", location: "Havana, Cuba", description: "Fidel Castro overthrows Batista dictatorship." },
  { title: "African Independence Year", year: 1960, category: "Politics", location: "Various African nations", description: "17 African nations gain independence from colonial powers." },
  { title: "Berlin Wall Built", year: 1961, category: "Politics", location: "Berlin, Germany", description: "East Germany builds wall dividing Berlin." },
  { title: "Yuri Gagarin in Space", year: 1961, category: "Exploration", location: "Baikonur, Kazakhstan", description: "First human in space orbits Earth." },
  { title: "Cuban Missile Crisis", year: 1962, category: "Politics", location: "Cuba", description: "Nuclear confrontation between U.S. and USSR." },
  { title: "JFK Assassination", year: 1963, category: "Politics", location: "Dallas, Texas", description: "President John F. Kennedy assassinated in Dallas." },
  { title: "Martin Luther King's 'I Have a Dream'", year: 1963, category: "Politics", location: "Washington, D.C.", description: "Historic speech during March on Washington." },
  { title: "Civil Rights Act", year: 1964, category: "Politics", location: "Washington, D.C.", description: "U.S. law prohibits discrimination based on race." },
  { title: "Vietnam War Escalates", year: 1965, category: "Conflict", location: "Saigon, Vietnam", description: "U.S. begins major combat operations in Vietnam." },
  { title: "Cultural Revolution Begins", year: 1966, category: "Politics", location: "Beijing, China", description: "Mao launches sociopolitical movement in China." },
  { title: "Six-Day War", year: 1967, category: "Conflict", location: "Jerusalem, Israel", description: "Israel defeats Arab coalition, captures territory." },
  { title: "Martin Luther King Assassinated", year: 1968, category: "Politics", location: "Memphis, Tennessee", description: "Civil rights leader shot in Memphis." },
  { title: "Prague Spring", year: 1968, category: "Revolution", location: "Prague, Czech Republic", description: "Reform movement crushed by Warsaw Pact invasion." },
  { title: "Moon Landing", year: 1969, category: "Exploration", location: "Moon", description: "Apollo 11 astronauts first humans to walk on Moon." },
  { title: "Woodstock Festival", year: 1969, category: "Culture", location: "Bethel, New York", description: "Iconic music festival defines counterculture era." },
  { title: "Kent State Shootings", year: 1970, category: "Politics", location: "Kent, Ohio", description: "National Guard kills four student protesters." },
  { title: "Microprocessor Invented", year: 1971, category: "Technology", location: "Santa Clara, California", description: "Intel creates first commercial microprocessor." },
  { title: "Watergate Break-in", year: 1972, category: "Politics", location: "Washington, D.C.", description: "Burglary leads to political scandal and Nixon's resignation." },
  { title: "Vietnam War Ends", year: 1973, category: "Conflict", location: "Paris, France", description: "Peace accords signed, U.S. withdraws from Vietnam." },
  { title: "Yom Kippur War", year: 1973, category: "Conflict", location: "Jerusalem, Israel", description: "Arab coalition attacks Israel on holy day." },
  { title: "Nixon Resigns", year: 1974, category: "Politics", location: "Washington, D.C.", description: "President Nixon resigns over Watergate scandal." },
  { title: "Fall of Saigon", year: 1975, category: "Conflict", location: "Ho Chi Minh City, Vietnam", description: "North Vietnam conquers South, ending Vietnam War." },
  { title: "First Personal Computer", year: 1975, category: "Technology", location: "Albuquerque, New Mexico", description: "Altair 8800 launched, beginning PC revolution." },
  { title: "Apple Computer Founded", year: 1976, category: "Technology", location: "Cupertino, California", description: "Steve Jobs and Steve Wozniak start Apple." },
  { title: "Star Wars Released", year: 1977, category: "Culture", location: "Los Angeles, California", description: "Groundbreaking science fiction film debuts." },
  { title: "Camp David Accords", year: 1978, category: "Politics", location: "Camp David, Maryland", description: "Egypt and Israel sign peace agreement." },
  { title: "Iranian Revolution", year: 1979, category: "Revolution", location: "Tehran, Iran", description: "Islamic revolution overthrows Shah of Iran." },
  { title: "Soviet Invasion of Afghanistan", year: 1979, category: "Conflict", location: "Kabul, Afghanistan", description: "USSR invades Afghanistan, beginning decade-long war." },
  { title: "Mount St. Helens Eruption", year: 1980, category: "Disaster", location: "Washington State", description: "Volcanic eruption kills 57, causes massive destruction." },
  { title: "CNN Launches", year: 1980, category: "Technology", location: "Atlanta, Georgia", description: "First 24-hour television news network begins broadcasting." },
  { title: "AIDS Epidemic Identified", year: 1981, category: "Science", location: "Los Angeles, California", description: "First cases of AIDS reported in United States." },
  { title: "Falklands War", year: 1982, category: "Conflict", location: "Falkland Islands", description: "Britain defeats Argentina in South Atlantic conflict." },
  { title: "Chernobyl Disaster", year: 1986, category: "Disaster", location: "Pripyat, Ukraine", description: "Nuclear reactor explodes, worst nuclear accident in history." },
  { title: "Black Monday Stock Crash", year: 1987, category: "Economy", location: "New York City, New York", description: "Largest single-day stock market crash in history." },
  { title: "Tiananmen Square Protests", year: 1989, category: "Politics", location: "Beijing, China", description: "Pro-democracy demonstrations violently suppressed." },
  { title: "Fall of Berlin Wall", year: 1989, category: "Politics", location: "Berlin, Germany", description: "Berlin Wall demolished, symbolizing end of Cold War." },
  { title: "Nelson Mandela Released", year: 1990, category: "Politics", location: "Cape Town, South Africa", description: "Anti-apartheid leader freed after 27 years in prison." },
  { title: "Gulf War", year: 1991, category: "Conflict", location: "Kuwait City, Kuwait", description: "Coalition forces liberate Kuwait from Iraq." },
  { title: "Soviet Union Dissolves", year: 1991, category: "Politics", location: "Moscow, Russia", description: "USSR officially dissolved, ending Cold War." },
  { title: "World Wide Web Goes Public", year: 1991, category: "Technology", location: "Geneva, Switzerland", description: "Tim Berners-Lee releases WWW to public." },
  { title: "Rwandan Genocide", year: 1994, category: "Conflict", location: "Kigali, Rwanda", description: "Mass slaughter kills 800,000 in 100 days." },
  { title: "Oklahoma City Bombing", year: 1995, category: "Conflict", location: "Oklahoma City, Oklahoma", description: "Domestic terrorist attack kills 168." },
  { title: "Dolly the Sheep Cloned", year: 1996, category: "Science", location: "Edinburgh, Scotland", description: "First mammal cloned from adult cell." },
  { title: "Hong Kong Returned to China", year: 1997, category: "Politics", location: "Hong Kong", description: "Britain transfers Hong Kong sovereignty to China." },
  { title: "Princess Diana Dies", year: 1997, category: "Culture", location: "Paris, France", description: "Princess of Wales killed in car crash." },
  { title: "Google Founded", year: 1998, category: "Technology", location: "Menlo Park, California", description: "Larry Page and Sergey Brin launch search engine." },
  { title: "Euro Currency Introduced", year: 1999, category: "Economy", location: "Frankfurt, Germany", description: "European Union launches common currency." },
  { title: "Columbine Shooting", year: 1999, category: "Conflict", location: "Littleton, Colorado", description: "School massacre kills 13, sparks gun debate." },

  // 2000s - Digital Age & War on Terror
  { title: "Millennium Celebration", year: 2000, category: "Culture", location: "Global", description: "World celebrates turn of millennium." },
  { title: "Human Genome Project Completed", year: 2000, category: "Science", location: "Washington, D.C.", description: "First draft of human genome sequence published." },
  { title: "September 11 Attacks", year: 2001, category: "Conflict", location: "New York City, New York", description: "Terrorist attacks kill nearly 3,000, change world." },
  { title: "War in Afghanistan Begins", year: 2001, category: "Conflict", location: "Kabul, Afghanistan", description: "U.S. invades Afghanistan after 9/11." },
  { title: "Euro Notes and Coins", year: 2002, category: "Economy", location: "Europe", description: "Euro currency physically circulated across Europe." },
  { title: "Space Shuttle Columbia Disaster", year: 2003, category: "Disaster", location: "Texas", description: "Shuttle disintegrates on reentry, killing seven." },
  { title: "Iraq War Begins", year: 2003, category: "Conflict", location: "Baghdad, Iraq", description: "U.S.-led coalition invades Iraq." },
  { title: "Facebook Founded", year: 2004, category: "Technology", location: "Cambridge, Massachusetts", description: "Mark Zuckerberg launches social network." },
  { title: "Indian Ocean Tsunami", year: 2004, category: "Disaster", location: "Indian Ocean", description: "Massive tsunami kills 230,000 in 14 countries." },
  { title: "YouTube Founded", year: 2005, category: "Technology", location: "San Bruno, California", description: "Video-sharing platform revolutionizes media." },
  { title: "Hurricane Katrina", year: 2005, category: "Disaster", location: "New Orleans, Louisiana", description: "Devastating hurricane floods New Orleans, kills 1,800." },
  { title: "Twitter Founded", year: 2006, category: "Technology", location: "San Francisco, California", description: "Microblogging platform launched." },
  { title: "iPhone Announced", year: 2007, category: "Technology", location: "San Francisco, California", description: "Apple unveils revolutionary smartphone." },
  { title: "Financial Crisis", year: 2008, category: "Economy", location: "New York City, New York", description: "Global financial crisis triggers Great Recession." },
  { title: "Barack Obama Elected", year: 2008, category: "Politics", location: "Washington, D.C.", description: "First African American U.S. president elected." },
  { title: "Swine Flu Pandemic", year: 2009, category: "Disaster", location: "Mexico City, Mexico", description: "H1N1 influenza pandemic spreads globally." },
  { title: "Arab Spring Begins", year: 2010, category: "Revolution", location: "Tunis, Tunisia", description: "Pro-democracy uprisings sweep Middle East and North Africa." },
  { title: "Haiti Earthquake", year: 2010, category: "Disaster", location: "Port-au-Prince, Haiti", description: "Devastating earthquake kills 300,000." },
  { title: "Osama bin Laden Killed", year: 2011, category: "Conflict", location: "Abbottabad, Pakistan", description: "U.S. forces kill al-Qaeda leader." },
  { title: "Fukushima Nuclear Disaster", year: 2011, category: "Disaster", location: "Fukushima, Japan", description: "Earthquake and tsunami cause nuclear meltdown." },
  { title: "Syrian Civil War Begins", year: 2011, category: "Conflict", location: "Damascus, Syria", description: "Uprising against Assad regime becomes brutal civil war." },
  { title: "Higgs Boson Discovered", year: 2012, category: "Science", location: "Geneva, Switzerland", description: "CERN confirms existence of 'God particle'." },
  { title: "Sandy Hook Shooting", year: 2012, category: "Conflict", location: "Newtown, Connecticut", description: "School shooting kills 26, mostly children." },
  { title: "Boston Marathon Bombing", year: 2013, category: "Conflict", location: "Boston, Massachusetts", description: "Terrorist attack kills 3 at marathon finish line." },
  { title: "Edward Snowden Leaks", year: 2013, category: "Politics", location: "Hong Kong", description: "NSA contractor reveals mass surveillance programs." },
  { title: "Crimea Annexed", year: 2014, category: "Conflict", location: "Crimea, Ukraine", description: "Russia annexes Crimean peninsula from Ukraine." },
  { title: "ISIS Declares Caliphate", year: 2014, category: "Conflict", location: "Mosul, Iraq", description: "Islamic State declares territory in Iraq and Syria." },
  { title: "Paris Climate Agreement", year: 2015, category: "Environment", location: "Paris, France", description: "196 nations agree to combat climate change." },
  { title: "Paris Terror Attacks", year: 2015, category: "Conflict", location: "Paris, France", description: "Coordinated attacks kill 130 in French capital." },
  { title: "Brexit Vote", year: 2016, category: "Politics", location: "London, England", description: "UK votes to leave European Union." },
  { title: "Donald Trump Elected", year: 2016, category: "Politics", location: "Washington, D.C.", description: "Businessman elected U.S. president in upset." },
  { title: "Women's March", year: 2017, category: "Politics", location: "Washington, D.C.", description: "Millions protest for women's rights globally." },
  { title: "Las Vegas Shooting", year: 2017, category: "Conflict", location: "Las Vegas, Nevada", description: "Deadliest mass shooting in U.S. history kills 60." },
  { title: "#MeToo Movement", year: 2017, category: "Culture", location: "Global", description: "Social movement against sexual harassment spreads worldwide." },
  { title: "North Korea Nuclear Tests", year: 2017, category: "Politics", location: "Pyongyang, North Korea", description: "North Korea tests intercontinental ballistic missiles." },
  { title: "Trump-Kim Singapore Summit", year: 2018, category: "Politics", location: "Singapore", description: "First meeting between U.S. and North Korean leaders." },
  { title: "Jamal Khashoggi Killed", year: 2018, category: "Politics", location: "Istanbul, Turkey", description: "Saudi journalist murdered in consulate." },
  { title: "Notre-Dame Fire", year: 2019, category: "Disaster", location: "Paris, France", description: "Historic cathedral badly damaged by fire." },
  { title: "Amazon Rainforest Fires", year: 2019, category: "Environment", location: "Amazon Basin, Brazil", description: "Record wildfires devastate Amazon rainforest." },
  { title: "Hong Kong Protests", year: 2019, category: "Revolution", location: "Hong Kong", description: "Mass pro-democracy protests against China." },
  { title: "COVID-19 Pandemic", year: 2020, category: "Disaster", location: "Wuhan, China", description: "Coronavirus pandemic spreads globally, kills millions." },
  { title: "George Floyd Protests", year: 2020, category: "Politics", location: "Minneapolis, Minnesota", description: "Global protests against police brutality and racism." },
  { title: "Joe Biden Elected", year: 2020, category: "Politics", location: "Washington, D.C.", description: "Biden defeats Trump in contentious election." },
  { title: "U.S. Capitol Riot", year: 2021, category: "Conflict", location: "Washington, D.C.", description: "Mob storms Capitol trying to overturn election." },
  { title: "COVID-19 Vaccines Distributed", year: 2021, category: "Science", location: "Global", description: "Mass vaccination campaigns begin worldwide." },
  { title: "U.S. Withdraws from Afghanistan", year: 2021, category: "Conflict", location: "Kabul, Afghanistan", description: "Taliban retakes Afghanistan as U.S. ends 20-year war." },
  { title: "James Webb Telescope Launched", year: 2021, category: "Science", location: "French Guiana", description: "Most powerful space telescope ever built launched." },
  { title: "Russia Invades Ukraine", year: 2022, category: "Conflict", location: "Kyiv, Ukraine", description: "Russia launches full-scale invasion of Ukraine." },
  { title: "Queen Elizabeth II Dies", year: 2022, category: "Politics", location: "Balmoral, Scotland", description: "Britain's longest-reigning monarch dies at 96." },
  { title: "ChatGPT Released", year: 2022, category: "Technology", location: "San Francisco, California", description: "OpenAI launches AI chatbot, revolutionizing AI." },
  { title: "Turkey-Syria Earthquake", year: 2023, category: "Disaster", location: "Gaziantep, Turkey", description: "Massive earthquake kills over 50,000." },
  { title: "Israel-Hamas War", year: 2023, category: "Conflict", location: "Gaza, Palestine", description: "Hamas attacks Israel, sparking major conflict." },
  { title: "Wagner Mutiny", year: 2023, category: "Politics", location: "Rostov, Russia", description: "Private military company briefly rebels against Russian government." },
  { title: "Maui Wildfires", year: 2023, category: "Disaster", location: "Maui, Hawaii", description: "Devastating fires destroy historic town of Lahaina." },
  { title: "AI Regulation Debates", year: 2023, category: "Technology", location: "Washington, D.C.", description: "Governments worldwide debate artificial intelligence regulation." },
  { title: "Historic Heat Waves", year: 2024, category: "Environment", location: "Global", description: "Record-breaking temperatures worldwide highlight climate crisis." },
  { title: "Total Solar Eclipse", year: 2024, category: "Science", location: "North America", description: "Total solar eclipse visible across North America." },
  { title: "Francis Scott Key Bridge Collapse", year: 2024, category: "Disaster", location: "Baltimore, Maryland", description: "Major bridge collapse after ship collision." },
  { title: "Advancement in Quantum Computing", year: 2024, category: "Technology", location: "Mountain View, California", description: "Major breakthroughs in quantum computer development." },
  { title: "Global Climate Summit", year: 2024, category: "Environment", location: "Dubai, UAE", description: "World leaders meet to address climate emergency." }
];

// Helper function to get events by year range
export function getEventsByYearRange(startYear, endYear) {
  return HISTORICAL_EVENTS.filter(event => 
    event.year >= startYear && event.year <= endYear
  );
}

// Helper function to get events by category
export function getEventsByCategory(category) {
  return HISTORICAL_EVENTS.filter(event => 
    event.category === category
  );
}

// Helper function to get random sample
export function getRandomEvents(count) {
  const shuffled = [...HISTORICAL_EVENTS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

